from os import system, name
from time import sleep
from clear import clear
clear()
print("You are walking on the highway when suddenly you see a truck driving.")
# sleep(3)
print("It's a... walmart truck???")
# sleep(1.5)
print("You quickly take out the flare gun Dwane gave you and as the truck is going by you shoot the driver in the head, instintly killing them.")
# sleep(4)
print("The truck goes off the road and into the ditch where you dispose of the body and decide you will live in the truck.")
# sleep(3)
print("You open the back and find that theres a bit of food, water, and toys.")
# sleep(2)
print("Most of the toys are not useful but behind all the toys you find something amazing. A crossbow. You can fight people and creatures now.")
# sleep(4)
print("You also find some bandages and wrap them around your laceration.")
# sleep(1.5)
print("You decide to go to sleep")
# sleep(5)
print("You wake up and as you look outside you see someone coming towards your truck holding a gun.")
#sleep(3)
print("You think to yourself: Wait, thats GABE.")
#sleep(2)
print("He comes up to the truck and opens it. He sees you and starts shooting.")
#sleep(2.5)
print("You: WAIT GABE ITS ME DONT SHOOT!!!")
#sleep(2)
print("Gabe: I don't care.")
#sleep(1.5)
print("He proceeds to shoot and eventuly shoots your leg. You play dead.")
#sleep(2)
print("He leaves the truck and as he is walking away you take your crossbow and shoot him in the chest. You then shoot him in the head.")
#sleep("3")
print("You start getting dizzy and pass out from blood loss.")
sleep(7)
print("You dont know how much time has passed but your gunshot wound stopped bleeding.")
#sleep(3)
print("You go to Gabe's body and take his phone. You call 911.")
#sleep(3)
print("You are airlifted to a hosbital where you recover over the span of a year.")
#sleep(3)
print("When you are discharged you find that your family is still alive because they were in the car driving to pick you up.")
#sleep(4)
print("You live out your years happy with your family. You end up writing a book about your struggles.")